name: Publish container

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Publish site"
    types:
      - completed

jobs:
  publishContainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAGES_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
