name: gh-pages publisher 🚀

on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v1
         with:
          node-version: 12
       - run: npm ci
       - run: git config user.name "Mitchell Fenner" && git config user.email "mitchfen@protonmail.com"
       - run: npm run deploy
         env:
          GH_TOKEN: ${{secrets.SECRET_GITHUB_TOKEN}}
