name: Publish site

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Build and Deploy
        run: |
          git config --global user.name $user_name
          git config user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: "Mitchell Fenner"
          user_email: "mitchfen@protonmail.com"
          github_token: ${{ secrets.GH_PAGES_SECRET }}
          repository: ${{ github.repository }}
