name: gh-pages publisher 🚀

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: git config user.name "Mitchell Fenner" && git config user.email "mitchfen@protonmail.com"
      - run: git remote set-url origin https://mitchfen:${{secrets.GITHUB_TOKEN}}>@github.com/mitchfen/mitchfen.github.io
      - run: npm run build
      - run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
