name: Check Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
