name: Check Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run deploy
