name: Testing

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Echo
        run: |
          echo "Hello, this is a branch action"
